---
title: "Actividad 1.11 Series de tiempo estacionarias"
author: "Raúl Correa Ocañas"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(TTR)
library(forecast)
```

# Problema 1

```{r Data}
y = c(17, 21, 19, 23, 18, 16, 20, 18, 22, 20, 15, 22)
t = 1:12

n = length(y)
```


```{r Moving Averages}
p = NA
e = NA
for(i in 1:(n-3)){
  p[i+3]=(y[i]+y[i+1]+y[i+2])/3; e[i+3] = p[i+3] -y[i+3]
}

maverages = data.frame(t,y,p,e^2)
maverages

CME=mean(e^2,na.rm=TRUE)
CME

plot(t, y, type="o", col="red")
x = (3+1):n
lines(x,p[x],type="o",col="blue")

```
```{r Moving Weighted Averages}
p2 = NA
e2 = NA
for(i in 1:(n-3)){
  p2[i+3]=(1/6)*y[i]+(2/6)*y[i+1]+(3/6)*y[i+2]; e2[i+3] = p2[i+3] - y[i+3]
}

mwaverages = data.frame(t,y,p2,e2^2)
mwaverages

CME=mean(e2^2,na.rm=TRUE)
CME

plot(t, y, type="o", col="red")
x2 = (3+1):n
lines(x2,p2[x2],type="o",col="blue")
```
```{r}
p3 = NA
e3 = NA

p3[1]=y[1]
p3[2]=y[1]

alfas = 0.05:0.5:0.05

for (a in alfas) {
  for(i in 3:n){
    p3[i]=a*y[i-1]+(1-a)*p3[i-1]; e3[i] = y[i]- p3[i]
  }
  # 
  # smooth_exp = data.frame(t,y,p3,e3^2)
  # smooth_exp
  
  CME=mean(e3^2,na.rm=TRUE)
  print(CME)
  # 
  # plot(t, y, type="o", col="red")
  # x3 = 2:n
  # lines(x3,p3[x3],type="o",col="blue")
}


```


# Ejercicio 2

```{r}

```

